### ISSUE TITLE
OAuth version?

### ISSUE THREAD

**Issue by ehalsey** [IntuitDeveloper/SampleApp-CRUD-.Net#10]
Is this example using OAuth 2.0?  If not, are there plans to update it?

**Comment by nimisha84** [comment]
Hi @ehalsey - This is still using tokens for Oauth1. We do have plans to provide the same sample in Oauth2 in about a week.

**Comment by nimisha84** [comment]
Please use this one for Oauth2-https://github.com/IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2/blob/master/README.md
