### ISSUE TITLE
OnFindAllAsyncCompleted doesn't work

### ISSUE THREAD

**Issue by GameScrub** [IntuitDeveloper/SampleApp-CRUD-.Net#11]
I copied the 
`

             dataService.OnFindAllAsyncCompleted += (sender, args) =>
             {
                manualEvent.Set();

                if (e.Error != null)
                {
                    // Error handling code                    
                }
                else if (e.Entities != null)
                {                    
                    if(e.Entities.Any())
                        result.AddRange((List<T>)e.Entities);
                }
            };
                                     `

and even though I can see the call and the data on fiddler it doesn't put the information on the args parameter.  If I use just the standard FindAll it does the same call on fiddler but it actually returns the value.

**Comment by nimisha84** [comment]
Hi Rafael, 

When you enable logging in the .Net SDK, is it logging the request and response or not?
To manage exception handling in your code: 

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging 

If you still do not see error details, enable logging in code using these three lines: 

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator); 
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true; 
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs"; 

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging 

If it is not logging there too then I can open a bug for SDK team to look into this.

**Comment by GameScrub** [comment]
I got the logs to save to the filesystem.  Here are the results...

There are two files one called Request and Response files.  The request files says "select * from Customer startPosition 1 maxResults 1000".

The results say..."{"QueryResponse":{"Customer":[{"Taxable":true,"BillAddr":{"Id":"2","Line1":"4581 Finch... " truncated to hide personal info.  Basically got data back, just like it says on fiddler as well.

But on visual studio with a breakpoint on the OnFindAllAsyncCompleted the args still say e.Entities = 0 and e.Errors = null;

**Comment by nimisha84** [comment]
As of now since you have details in the details in the logs, I will open an enhancement request for team to see if this support can be added in future in the V3 SDK.
