### ISSUE TITLE
Where to get Configuration details

### ISSUE THREAD

**Issue by pateljagdishk** [IntuitDeveloper/SampleApp-CRUD-.Net#13]
Hello,

I was trying this simple CRUD app however I am unable to find the value for the configuration defined in web.config file under my app in qbo. Can someone point me where can I get those details - 

<add key="ConsumerKey" value="" />
<add key="ConsumerSecret" value="" />
<add key="AccessToken" value=""/>
<add key="AccessTokenSecret" value=""/>
<add key="realmId" value=""/>

Under myapp's key I can see ClientKey and ClientSecret but nothing that are asked above.

**Comment by nbhambhani** [comment]
Hi,
This sample uses OAuth1 credentials and your app uses OAuth2. Please refer to this sample instead:
https://github.com/IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2

**Comment by pateljagdishk** [comment]
This is webapplication. I am looking for Windows application. Do you have
any such sample?

Jagdish

**Comment by nbhambhani** [comment]
Hello,
You will still need a web component in your Windows application which does OAuth2 flow and handles redirect. Without this component, you can't create an app which uses QuickBooks APIs. For that you can refer to the sample I mentioned before.

**Comment by pateljagdishk** [comment]
Hey Nikita,

I am getting intermittent error when try to query Item object.

URL -
https://quickbooks.api.intuit.com/v3/company/123145999406989/query?minorversion=12&requestid=7b04404be2f940d8afc81449e35b3c52

Response -
HTTP/1.1 500 Server Error
Server: nginx
Date: Thu, 31 May 2018 05:42:33 GMT
Content-Type: application/json
Content-Length: 369
Connection: keep-alive
Keep-Alive: timeout=5

{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=InternalServerError;
errorCode=003100;
statusCode=500","detail":null,"code":"3100","element":null}],"type":"SERVICE"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1527745353516,"status":null,"cdcresponse":[]}


This code was working just fine. However today i am getting intermittent
error when I make a request.

Is there any issue going on at quickbook side which might be affecting me?
Let me know if you need anything else in order to investigate the issue.

Jagdish

**Comment by nbhambhani** [comment]
Hi Jagdish,
We had a QBO API outage at the time you made this request. It's stable now, can you try again?
Nikita

**Comment by pateljagdishk** [comment]
Yeap it is working now.

Thanks.
