### ISSUE TITLE
Unable to write an amount to QBO Sandbox

### ISSUE THREAD

**Issue by raheel0452** [IntuitDeveloper/SampleApp-CRUD-.Net#14]
Hi,

Thank you for the sample app. 

Am not able to write any amount to QBO Sandbox environment. I've referred to code in 'QBOHelper.cs' and used 'CreateInvoice' method to write Invoice data to QBO. Text fields are getting written correctly however amount is always written as zero.

Code snippet from QBOHelper.cs

            Invoice invoice = new Invoice();
            invoice.Deposit = new Decimal(10.00);
            invoice.DepositSpecified = true;

Please advise if any additional step need to be performed ?

Thanks

**Comment by nbhambhani** [comment]
Hi @raheel0452 
Can you enable logging and post the API request and response please? Follow the steps for Request and Response logging section on this page:
https://developer.intuit.com/docs/00_quickbooks_online/2_build/40_sdks/01_.net/0028_logging

**Comment by raheel0452** [comment]
Thank you,

This is solved now. Enabling logging helped to find the issue.

Thanks again!
