### ISSUE TITLE
No apis available for "Expense"

### ISSUE THREAD

**Issue by zuberspathan** [IntuitDeveloper/SampleApp-CRUD-.Net#15]
No apis available to create, read, update, delete for expense, no helper method available, is there any indirect way to use it.

**Comment by nbhambhani** [comment]
Hello @zuberspathan 
The API name for Expense is Purchase, we have CRUD operations supported for it and demo-ed in this sample app
https://github.com/IntuitDeveloper/SampleApp-CRUD-.Net/blob/870452debfce50473998c583e659eb4f47b90e6a/SampleApp_CRUD_.Net/SampleApp_CRUD_.Net/Entities/TransactionEntities/Purchase.cs
