### ISSUE TITLE
Not able to do invoice payment, it showing "unapplied"

### ISSUE THREAD

**Issue by zuberspathan** [IntuitDeveloper/SampleApp-CRUD-.Net#16]
We are checking for the different status criteria, we are getting "open", "overdue"  but when tried to do payment for bill its showing "open" instead of paid and "unapplied" instead of close ... Please check "Create Payment" method from QBO Helper.  I have seen the API Explorer for request body its showing some "LinkedTxn" so i have added that one too but its showing only "unapplied" status

**Comment by nimisha84** [comment]
Is this resolved? The status for Payment will show as applied only when it is for same customer and the linked txn was added correctly. Creating Invoice and Payment on API explorer and then comparing the read response for them with your code's logs will help you sort the issue.
For logging refer-
https://developer.intuit.com/docs/00_quickbooks_online/2_build/40_sdks
