### ISSUE TITLE
Build issues and poorly documented, missing other objects 

### ISSUE THREAD

**Issue by mach37** [IntuitDeveloper/SampleApp-CRUD-.Net#2]
hi,

The build does not run, can you provide two separate helper classes, I need combine data from our local system before I call the online webservices.

- [ ] Methods and objects to integrate **with the desktop version**
- [ ] Methods and objects to integrate with the online version

- [ ] Please list the steps in a read me on **what needs to be stepup before connecting to local and online version**.
- [ ] Please include a way of checking the version of the installed QB and the compatibility of the SDK

**Comment by nimisha84** [comment]
All this info can be accessed on our website-
developer.intuit.com
The steps to connect to local/sandbox and Prod QBO company is also mentioned in the Test class.
You should report any issues that you have on developer.intuit.com->Help to get help after you have read the docs.

**Comment by nimisha84** [comment]
Again this is only for QBO. The desktop SDK is diff and does not uses API . It can be accessed here-
https://developer.intuit.com/docs/0200_quickbooks_desktop/0400_tools/0000_overview
