### ISSUE TITLE
Needs current ASP MVC web api services not old and outdated aspx

### ISSUE THREAD

**Issue by mach37** [IntuitDeveloper/SampleApp-CRUD-.Net#3]
Hi,

this sample is from 2017 and its using 10 yr old aspx calls, can you please provide a sample with the current web api

and include the steps/dev guide to setup hand shake and confirmation.

**Comment by nimisha84** [comment]
The very first disclaimer I want to post here is that none of the desktop calls are supported by any of the .Net sample app posted here.

**Comment by nimisha84** [comment]
The sample here is written to provide guidance on how to make the api calls in the simplest way.
Not many of our devs use webapi.
If you want to look at some of the other sample apps, then we do have MVC5 sample.
