### ISSUE TITLE
The designer file is missing in the build

### ISSUE THREAD

**Issue by mach37** [IntuitDeveloper/SampleApp-CRUD-.Net#4]
This file is empty/default versoin and nothing shows up on the [designer, please fix](https://github.com/IntuitDeveloper/SampleApp-CRUD-.Net/blob/master/SampleApp_CRUD_.Net/SampleApp_CRUD_.Net/TestQBOAPICalls.aspx.designer.cs)

**Comment by nimisha84** [comment]
This sample app is not meant to have any UI. It is required by the devs to run the sample app and debug. Enable logging from sample app as mentioned on Test class to get details on the calls.
