### ISSUE TITLE
Nuget Package Config

### ISSUE THREAD

**Issue by ghost** [IntuitDeveloper/SampleApp-CRUD-.Net#6]
Thanks for the sample code.

The package.config has some typos and missing some characters.  Also, it's not neccessary to commit your package folder. The nuget client should download these packages at build time.

I have submitted the following PR to fix these mistakes. https://github.com/IntuitDeveloper/SampleApp-CRUD-.Net/pull/7

**Comment by nimisha84** [comment]
Thanks! The suggested changes have been made.
